### ISSUE TITLE
Задание 3: добавить свойства и поведение для своего животного

### ISSUE THREAD

**Issue by bourd0n** [bourd0nOrg/cats_world#15]
Добавить свойства и поведение для своего животного. 
Необходимый минимум:  
- животное должно быть живым (используем интерфейс Alive)
- класс должен наследоваться от класса Pet
- минимум 2-3 свойства вашего животного
- конструктор, где проставляются свойства.
- минимум 2-3 метода, характеризующие поведение животного. Фантазия приветствуется:)
- если вам необходимы другие классы, можно их создавать
- сделать Pull Request в основной репозиторий. В описании Pull Request'a опишите что это за животное и что умеет

**Срок : 13.04**

**Comment by bourd0n** [comment]
@bourd0nOrg/prog_methods_team 

Также прошу обратить внимание, что на основной странице https://github.com/bourd0nOrg/cats_world появилась ссылка на таблицу с текущей успеваемостью.

**Comment by bourd0n** [comment]
@bourd0nOrg/prog_methods_team 

Напоминаю о deadline на задание. Сегодня вечером новые Pull Request'ы (а также изменения в текущие) уже приниматься не будут.

**Comment by IvanEgorov** [comment]
Сделал 3 задания, не могу сделать merge, не знаю почему
