### ISSUE TITLE
Задание 4 : сделать merge изменений из основного репозитория в свой репозиторий

### ISSUE THREAD

**Issue by bourd0n** [bourd0nOrg/cats_world#16]
_Описание и детали выполнения задания будут даны на занятии 06.04._

**Comment by bourd0n** [comment]
@bourd0nOrg/prog_methods_team 

> Описание и детали выполнения задания будут даны на занятии 06.04.

Обращаю внимание, что необходимым условием для выполнения этого задания является выполненное задание 1, поэтому лучше успеть это сделать до занятия.

**Comment by Anastasiya4895** [comment]
Здравствуйте не могу дома обновить. Пытаясь сделать git pull высвечивается вот что 
$ git pull
Updating 84b0a7b..291844d
error: Your local changes to the following files would be overwritten by merge:
src/com/alex/main/MainClass.java
Please, commit your changes or stash them before you can merge.
Aborting
Я не понимаю, что это (

**Comment by bourd0n** [comment]
@Anastasiya4895 видимо ты дома поменяла класс MainClass но не сделала commit.
Есть 2 опции:
1. сделать commit
2. "Спрятать" локальные изменения. Делается командой `git stash`. После этого `git pull` должен пройти, но локальные изменения не будут закоммичены.

Сообщи, пожалуйста, что все ок.

**Comment by Anastasiya4895** [comment]
Спасибо большое все заработало)

**Comment by bourd0n** [comment]
@bourd0nOrg/prog_methods_team 

Мерж должен быть отображен тут https://github.com/bourd0nOrg/cats_world/network
